import { ReactNode } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

type LegalPolicyType = "privacy" | "terms";

interface LegalPolicyDialogProps {
  type: LegalPolicyType;
  children: ReactNode;
}

const POLICY_CONTENT: Record<
  LegalPolicyType,
  {
    title: string;
    effectiveDate: string;
    intro: string;
    sections: Array<{ heading: string; body: string }>;
  }
> = {
  privacy: {
    title: "Privacy Policy",
    effectiveDate: "May 19, 2026",
    intro: "This policy explains how Era Composer Chat handles information when you use the app.",
    sections: [
      {
        heading: "Data We Process",
        body: "The app processes your chat prompts and related app state in order to generate responses. Some settings and temporary conversation state may be stored in your browser so the app works as expected.",
      },
      {
        heading: "Cookies and Local Storage",
        body: "We use functional browser storage (including local storage and a basic preference cookie used for interface behavior). These are used to improve usability, not for advertising profiles.",
      },
      {
        heading: "Retention",
        body: "Conversations are not intended to be permanently stored as a user account history. Data retained by your browser can be cleared by you at any time.",
      },
      {
        heading: "Third-Party Services",
        body: "The app relies on external AI services to generate responses. Their processing may be subject to their own privacy terms.",
      },
      {
        heading: "Your Choices",
        body: "You may stop using the app at any time and clear browser data (cookies/local storage) through your browser settings.",
      },
    ],
  },
  terms: {
    title: "Terms of Use",
    effectiveDate: "May 19, 2026",
    intro: "Era Composer Chat is provided for educational and entertainment purposes. By using this app, you agree to these terms.",
    sections: [
      {
        heading: "Educational Purpose",
        body: "The app helps users explore music history through AI-generated conversations inspired by public-domain historical figures and materials. Not all composers are available to chat with due to copyright, but they're included for their historical importance.",
      },
      {
        heading: "AI-Generated Responses",
        body: "Responses are generated by AI and may contain inaccuracies. Content should not be treated as professional, legal, medical, or academic advice.",
      },
      {
        heading: "Acceptable Use",
        body: "You agree not to misuse the service, attempt unauthorized access, or use the app in ways that violate applicable laws and regulations.",
      },
      {
        heading: "Availability",
        body: "The app may be updated, paused, or discontinued at any time without prior notice.",
      },
    ],
  },
};

const LegalPolicyDialog = ({ type, children }: LegalPolicyDialogProps) => {
  const content = POLICY_CONTENT[type];

  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-w-3xl p-0 duration-0 data-[state=open]:animate-none data-[state=closed]:animate-none sm:max-h-[88dvh]">
        <div className="max-h-[88dvh] overflow-y-auto p-5 sm:p-8">
          <DialogHeader className="mb-6 text-left">
            <DialogTitle>{content.title}</DialogTitle>
            <DialogDescription>
              Effective date: {content.effectiveDate}
            </DialogDescription>
          </DialogHeader>

          <section className="space-y-6 text-sm leading-6 text-foreground">
            <p>{content.intro}</p>

            {content.sections.map((section) => (
              <div key={section.heading}>
                <h2 className="mb-2 text-base font-medium">{section.heading}</h2>
                <p className="text-muted-foreground">{section.body}</p>
              </div>
            ))}

            <div>
              <h2 className="mb-2 text-base font-medium">Contact</h2>
              <p className="text-muted-foreground">
                Questions can be sent to{" "}
                <a
                  href="mailto:voicevoz321@gmail.com"
                  className="text-primary hover:underline focus:outline-none focus-visible:ring-1 focus-visible:ring-primary focus-visible:rounded-sm"
                >
                  voicevoz321@gmail.com
                </a>
                .
              </p>
            </div>
          </section>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default LegalPolicyDialog;
