import { useEffect } from "react";
import { useNavigate } from "react-router-dom";

const Terms = () => {
  const navigate = useNavigate();

  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = "";
    return () => {
      document.body.style.overflow = prev;
    };
  }, []);

  return (
    <main
      className="h-[100dvh] overflow-y-auto bg-background text-foreground"
      aria-labelledby="terms-title"
    >
      <header className="sticky top-0 z-20 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/70">
        <div className="container mx-auto flex max-w-3xl items-center px-4 py-3">
          <button
            type="button"
            onClick={() => navigate("/")}
            className="text-sm text-primary hover:underline focus:outline-none focus-visible:ring-1 focus-visible:ring-primary focus-visible:rounded-sm"
          >
            Close
          </button>
        </div>
      </header>

      <div className="container mx-auto max-w-3xl px-4 py-8 md:py-10">
        <article className="rounded-xl border border-border/70 bg-card/40 p-5 shadow-sm md:p-8">
          <header className="mb-8">
            <h1 id="terms-title" className="text-2xl font-semibold">
              Terms of Use
            </h1>
            <p className="mt-2 text-sm text-muted-foreground">
              Effective date: May 19, 2026
            </p>
          </header>

          <section className="space-y-6 text-sm leading-6">
            <p>
              Era Composer Chat is provided for educational and entertainment
              purposes. By using this app, you agree to these terms.
            </p>

            <div>
              <h2 className="mb-2 text-base font-medium">Educational Purpose</h2>
              <p className="text-muted-foreground">
                The app helps users explore music history through AI-generated
                conversations inspired by public-domain historical figures and
                materials. Not all composers are available to chat with due to copyright, but they're included for their historical importance.
              </p>
            </div>

            <div>
              <h2 className="mb-2 text-base font-medium">
                AI-Generated Responses
              </h2>
              <p className="text-muted-foreground">
                Responses are generated by AI and may contain inaccuracies.
                Content should not be treated as professional, legal, medical,
                or academic advice.
              </p>
            </div>

            <div>
              <h2 className="mb-2 text-base font-medium">Acceptable Use</h2>
              <p className="text-muted-foreground">
                You agree not to misuse the service, attempt unauthorized
                access, or use the app in ways that violate applicable laws and
                regulations.
              </p>
            </div>

            <div>
              <h2 className="mb-2 text-base font-medium">Availability</h2>
              <p className="text-muted-foreground">
                The app may be updated, paused, or discontinued at any time
                without prior notice.
              </p>
            </div>

            <div>
              <h2 className="mb-2 text-base font-medium">Contact</h2>
              <p className="text-muted-foreground">
                Questions about these terms can be sent to{" "}
                <a
                  href="mailto:voicevoz321@gmail.com"
                  className="text-primary hover:underline focus:outline-none focus-visible:ring-1 focus-visible:ring-primary focus-visible:rounded-sm"
                >
                  voicevoz321@gmail.com
                </a>
                .
              </p>
            </div>
          </section>
        </article>
      </div>
    </main>
  );
};

export default Terms;
